### COMMAND OPTIONS

# If you're using a specific nasm binary, run make like:
# NASM=/path/to/nasm make -e
NASM = nasm
# If running on OS X, change this to hdiutil
DISKUTIL = parted


### MAKE OPTIONS

# KERNELPATH specifies a path to a binary file to chain-load from pure64.sys.
# Used for "make pxe" as well as the filesystem variants, where it overrides
# the default kernel load logic for that filesystem (making the KERNEL macro
# irrelevant). MUST be specified for "make pxe", e.g.:
# make pxe KERNELPATH=/path/to/kernel64.sys
KERNELPATH = ""
# HDD specifies the hard disk interface type.
# Options: PIO or AHCI
HDD = PIO
# FS specifies the expected filesystem (not relevant for PXE).
# Options: FAT16 or BMFS
FS = FAT16
# LOADER specifies the name of the pure64.sys file. Only used if FS=FAT16.
LOADER = "PURE64  SYS"
# KERNEL specifies the name of the kernel64.sys file. Only used if FS=FAT16.
KERNEL = "KERNEL64SYS"
# IMAGESIZE specifies the desired size (in MiB) of the output disk image
# generated by the "make vmdk" and "make raw" commands. Defaults to 10MiB.
IMAGESIZE = 16


_build:
	mkdir -p build

pxestart.bin: _build
	${NASM} -Isrc/ src/bootsectors/pxestart.asm -o build/pxestart.bin

FAT16mbr.bin: _build
	${NASM} -Isrc/ src/bootsectors/fat16.asm -o build/FAT16mbr.bin \
		-dLOADER='${LOADER}'

BMFSmbr.bin: _build
ifeq (${KERNELPATH},"")
	${NASM} -Isrc/ src/bootsectors/bmfs.asm -o build/BMFSmbr.bin
else
	${NASM} -Isrc/ src/bootsectors/bmfs.asm -o build/BMFSmbr.bin \
		 -dPURE64_CHAIN_LOADING
endif

pure64.sys: _build
ifeq (${KERNELPATH},"")
	${NASM} -Isrc/ src/pure64.asm -o build/pure64.sys -dHDD=${HDD} -dFS=${FS} \
		-dLOADER='${LOADER}' -dKERNEL='${KERNEL}'
else
	${NASM} -Isrc/ src/pure64.asm -o build/pure64.sys -dHDD=${HDD} -dFS=${FS} \
		-dLOADER='${LOADER}' -dKERNEL='${KERNEL}' -dPURE64_CHAIN_LOADING
	cat build/pure64.sys ${KERNELPATH} > build/pure64chain.sys
	mv build/pure64chain.sys build/pure64.sys
endif

pxe: _build pxestart.bin pure64.sys
	cat build/pxestart.bin build/pure64.sys > build/pxeboot.bin

img: _build ${FS}mbr.bin pure64.sys
ifeq (${FS},BMFS)
	dd if=/dev/zero of=build/system.img bs=1048576 count=${IMAGESIZE}
	dd if=build/${FS}mbr.bin of=build/system.img bs=512 conv=notrunc
	dd if=build/pure64.sys of=build/system.img bs=512 conv=notrunc oseek=16
else
ifeq (${DISKUTIL},parted)
	# Using parted to create FAT16 image
	dd if=/dev/zero of=build/system.img bs=1048576 count=${IMAGESIZE}
	# Set up the FAT16 disk image with a bootable partition
	parted build/system.img mktable msdos
	parted build/system.img "mkpart p fat16 1 -0"
	parted build/system.img mkfs y 1 fat16
	parted build/system.img toggle 1 boot
	# Copy the MBR, leaving the partition table intact
	dd if=build/${FS}mbr.bin of=build/system.img bs=446 count=1 conv=notrunc
	# Mount the image and copy pure64.sys to it
endif
ifeq (${DISKUTIL},hdiutil)
	# Using hdiutil to create FAT16 image with pure64.sys in it
	mkdir -p build/imgsrc
	cp build/pure64.sys build/imgsrc/PURE64.SYS
	hdiutil create -ov -fs "MS-DOS FAT16" -megabytes ${IMAGESIZE} \
		-o build/system -srcdir build/imgsrc -layout MBRSPUD \
		-format UDTO -nospotlight -quiet
	mv build/system.cdr build/system.img
	dd if=build/${FS}mbr.bin of=build/system.img bs=446 count=1 conv=notrunc
	rm -r build/imgsrc
endif
endif

vmdk: _build img
	cp build/system.img build/system-flat.vmdk

clean:
	rm -r build

