/* =============================================================================
 * Pure64 -- a 64-bit OS/software loader written in Assembly for x86-64 systems
 * Copyright (C) 2008-2017 Return Infinity -- see LICENSE.TXT
 * =============================================================================
 */

#include <pure64/fs.h>
#include <pure64/file.h>
#include <pure64/error.h>
#include <pure64/gpt.h>
#include <pure64/mbr.h>
#include <pure64/stream.h>
#include <pure64/string.h>
#include <pure64/uuid.h>

#include "fstream.h"
#include "util.h"

/* Generated by resource compiler */
#include "mbr-data.h"
#include "multiboot-data.h"
#include "multiboot2-data.h"
#include "pure64-data.h"
#include "pxe-data.h"
#include "stage-three-data.h"

#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

/* * * * * *
 * Constants
 * * * * * */

#ifndef PURE64_DISK_LOCATION
#define PURE64_DISK_LOCATION (PURE64_FS_SECTOR * 512)
#endif

#ifndef PURE64_MINIMUM_DISK_SIZE
#define PURE64_MINIMUM_DISK_SIZE (1 * 1024 * 1024)
#endif

#ifndef PURE64_DEFAULT_DISK_UUID
#define PURE64_DEFAULT_DISK_UUID "74a7c14a-711d-4293-a731-569ca656799e"
#endif

/* * * * * * * * * * * * * * * * *
 * Memory Allocation Declarations
 * * * * * * * * * * * * * * * * */

void *pure64_malloc(uint64_t size) {
	return malloc(size);
}

void *pure64_realloc(void *addr, uint64_t size) {
	return realloc(addr, size);
}

void pure64_free(void *addr) {
	free(addr);
}

/* * * * * * * * * * * * * *
 * Command Line Declarations
 * * * * * * * * * * * * * */

/** Compares an option with a command
 * line argument. This function checks
 * both short and long options.
 * @param arg The argument from the command line.
 * @param opt The long option (the two '--' are added
 * automatically).
 * @param s_opt The letter representing the short option.
 * @returns True if the argument is a match, false
 * if the argument is not a match.
 * */

static bool check_opt(const char *arg,
                      const char *opt,
                      char s_opt) {

	/* create a string version
	 * of the short option */
	char s_opt3[3];
	s_opt3[0] = '-';
	s_opt3[1] = s_opt;
	s_opt3[2] = 0;
	if (strcmp(s_opt3, arg) == 0)
		return true;

	if ((arg[0] == '-')
	 && (arg[1] == '-')
	 && (strcmp(&arg[2], opt) == 0))
		return true;

	return false;
}

/** Prints the help message.
 * @param argv0 The name of the program.
 * */

static void print_help(const char *argv0) {
	printf("Usage: %s [options] <command>\n", argv0);
	printf("\n");
	printf("Options:\n");
	printf("\t--file, -f : Specify the path to the Pure64 file.\n");
	printf("\t--help, -h : Print this help message.\n");
	printf("\n");
	printf("Commands:\n");
	printf("\tinit  : Initialize the disk image.\n");
	printf("\tcat   : Print the contents of a file.\n");
	printf("\tcp    : Copy file from host file system to Pure64 image.\n");
	printf("\tls    : List directory contents.\n");
	printf("\tmkdir : Create a directory.\n");
	printf("\trm    : Remove a file.\n");
	printf("\trmdir : Remove a directory.\n");
}

static bool is_opt(const char *argv) {
	if (argv[0] == '-')
		return true;
	else
		return false;
}

/* * * * * * * * * * * *
 * Command Declarations
 * * * * * * * * * * * */

static int pure64_init(const char *filename, int argc, const char **argv) {

	const char *config_path = "pure64-config.txt";

	for (int i = 0; i < argc; i++) {
		if (strcmp(argv[i], "--config") == 0) {
			if ((i + 1) >= argc) {
				fprintf(stderr, "Config path not specified.\n");
				return EXIT_FAILURE;
			}
			config_path = argv[i + 1];
			i++;
		} else if (argv[i][0] == '-') {
			fprintf(stderr, "Unknown option: %s\n", argv[i]);
			return EXIT_FAILURE;
		} else {
			fprintf(stderr, "Unknown argument: %s\n", argv[i]);
			return EXIT_FAILURE;
		}
	}

	struct pure64_util util;

	pure64_util_init(&util);

	int err = pure64_util_create_disk(&util, config_path, filename);
	if (err != 0) {
		fprintf(stderr, "Failed to create disk image: %s\n", pure64_strerror(err));
		pure64_util_done(&util);
		return EXIT_FAILURE;
	}

	pure64_util_done(&util);

	return EXIT_SUCCESS;

#if 0
	int err;
	const char *disk_uuid_str;
	struct pure64_uuid disk_uuid;
	int i;
	unsigned long long int fs_size;
	uint64_t disk_size;
	struct pure64_mbr mbr;
	struct pure64_gpt gpt;
	struct pure64_fstream disk;
	struct pure64_fs fs;

	disk_uuid_str = NULL;
	fs_size = 32 * 1024 * 1024;

	for (i = 0; i < argc; i++) {
		if (strcmp(argv[i], "--disk-uuid") == 0) {
			disk_uuid_str = argv[i + 1];
			i++;
		} else if (strcmp(argv[i], "--fs-size") == 0) {
			if ((i + 1) >= argc) {
				fprintf(stderr, "File system size not specified.\n");
				return EXIT_FAILURE;
			} else if (sscanf(argv[i + 1], "%llu", &fs_size) != 0) {
				fprintf(stderr, "Malformed file system: %s\n", argv[i + 1]);
				return EXIT_FAILURE;
			}
		} else {
			fprintf(stderr, "Unknown option '%s'\n", argv[i]);
			return EXIT_FAILURE;
		}
	}

	/* pad file system size to nearest sector */

	fs_size = ((fs_size + 511) / 512) * 512;

	if (disk_uuid_str == NULL) {
		fprintf(stderr, "Warning: Disk UUID not specified.\n");
		disk_uuid_str = PURE64_DEFAULT_DISK_UUID;
	}

	err = pure64_uuid_parse(&disk_uuid, disk_uuid_str);
	if (err != 0) {
		fprintf(stderr, "Malformed disk UUID string.\n");
		return EXIT_FAILURE;
	}

	/* Open the disk file */

	pure64_fstream_init(&disk);

	err = pure64_fstream_open(&disk, filename, "wb+");
	if (err != 0) {
		fprintf(stderr, "Failed to open '%s' for writing.\n", filename);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	/* Resize the file based on the file system
	 * size and all the static data. */

	disk_size = PURE64_GPT_MINIMUM_SIZE;
	disk_size += pure64_data_size;
	disk_size += stage_three_data_size;
	disk_size += fs_size;

	err = pure64_fstream_resize(&disk, disk_size);
	if (err != 0) {
		fprintf(stderr, "Failed to resize '%s'.\n", filename);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	/* Write the master boot record */

	err = pure64_stream_set_pos(&disk.base, 0);
	if (err != 0) {
		fprintf(stderr, "Failed to seek to MBR.\n");
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_stream_write(&disk.base, mbr_data, mbr_data_size);
	if (err != 0) {
		fprintf(stderr, "Failed to write multiboot record.\n");
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	/* Initialize the GPT structure */

	pure64_gpt_init(&gpt);

	pure64_gpt_set_disk_uuid(&gpt, &disk_uuid);

	/* Format the GPT structure */

	err = pure64_gpt_format(&gpt, disk_size);
	if (err != 0) {
		fprintf(stderr, "Failed to format GPT: %s\n", pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	/* Initialize stage two partition */

	err = pure64_gpt_set_entry_type(&gpt, 0, PURE64_UUID_STAGE_TWO);
	if (err != 0) {
		fprintf(stderr, "Failed to set GPT entry type: %s\n", pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_gpt_set_entry_name(&gpt, 0, u"Pure64 Stage Two");
	if (err != 0) {
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_gpt_set_entry_size(&gpt, 0, pure64_data_size);
	if (err != 0) {
		fprintf(stderr, "Failed to set GPT entry #%u size: %s\n", 0, pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_stream_set_pos(&disk.base, gpt.primary_entries[0].first_lba * 512);
	if (err != 0) {
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_stream_write(&disk.base, pure64_data, pure64_data_size);
	if (err != 0) {
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	/* Initialize stage three partition */

	err = pure64_gpt_set_entry_type(&gpt, 1, PURE64_UUID_STAGE_THREE);
	if (err != 0) {
		fprintf(stderr, "Failed to set GPT entry type: %s\n", pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_gpt_set_entry_name(&gpt, 1, u"Pure64 Stage Three");
	if (err != 0) {
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_gpt_set_entry_size(&gpt, 1, stage_three_data_size);
	if (err != 0) {
		fprintf(stderr, "Failed to set GPT entry #%u size: %s\n", 1, pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_stream_set_pos(&disk.base, gpt.primary_entries[1].first_lba * 512);
	if (err != 0) {
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_stream_write(&disk.base, stage_three_data, stage_three_data_size);
	if (err != 0) {
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	/* Initialize file system partition */

	err = pure64_gpt_set_entry_type(&gpt, 2, PURE64_UUID_FILE_SYSTEM);
	if (err != 0) {
		fprintf(stderr, "Failed to set GPT entry type: %s\n", pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_gpt_set_entry_name(&gpt, 2, u"Pure64 File System");
	if (err != 0) {
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	err = pure64_gpt_set_entry_size(&gpt, 2, 4096);
	if (err != 0) {
		fprintf(stderr, "Failed to set GPT entry #%u size: %s\n", 2, pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	pure64_fs_init(&fs);

	err = pure64_stream_set_pos(&disk.base, gpt.primary_entries[2].first_lba * 512);
	if (err != 0) {
		fprintf(stderr, "Failed to seek to file system partition: %s\n", pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		pure64_fs_free(&fs);
		return EXIT_FAILURE;
	}

	err = pure64_fs_make_dir(&fs, "/boot");
	if (err != 0) {
		fprintf(stderr, "Failed to create '/boot' directory: %s\n", pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		pure64_fs_free(&fs);
		return EXIT_FAILURE;
	}

	err = pure64_fs_export(&fs, &disk.base);
	if (err != 0) {
		fprintf(stderr, "Failed to export file system: %s\n", pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		pure64_fs_free(&fs);
		return EXIT_FAILURE;
	}

	pure64_fs_free(&fs);

	/* Export the GPT structure to disk */

	err = pure64_gpt_export(&gpt, &disk.base);
	if (err != 0) {
		fprintf(stderr, "Failed to export GPT to '%s': %s\n", filename, pure64_strerror(err));
		pure64_gpt_done(&gpt);
		pure64_fstream_done(&disk);
		return EXIT_FAILURE;
	}

	/* Update the MBR to load to the second
	 * and third stage boot loaders properly. */

	err = pure64_stream_set_pos(&disk.base, 0x00);
	if (err != 0) {
		fprintf(stderr, "Failed to seek to MBR: %s\n", pure64_strerror(err));
		pure64_fstream_done(&disk);
		pure64_gpt_done(&gpt);
		return EXIT_FAILURE;
	}

	pure64_mbr_zero(&mbr);

	err = pure64_mbr_read(&mbr, &disk.base);
	if (err != 0) {
		fprintf(stderr, "Failed to read MBR: %s\n", pure64_strerror(err));
		pure64_fstream_done(&disk);
		pure64_gpt_done(&gpt);
		return EXIT_FAILURE;
	}

	mbr.st2dap.sector = gpt.primary_entries[0].first_lba;
	mbr.st2dap.sector_count = (pure64_data_size + 511) / 512;
	mbr.st3dap.sector = gpt.primary_entries[1].first_lba;
	mbr.st3dap.sector_count = (stage_three_data_size + 511) / 512;

	err = pure64_mbr_write(&mbr, &disk.base);
	if (err != 0) {
		fprintf(stderr, "Failed to write MBR: %s\n", pure64_strerror(err));
		pure64_fstream_done(&disk);
		pure64_gpt_done(&gpt);
		return EXIT_FAILURE;
	}

	/* Release memory and exit. */

	pure64_gpt_done(&gpt);

	pure64_fstream_done(&disk);

	return EXIT_SUCCESS;
#endif
}

static int pure64_mkgpt(struct pure64_util *util, int argc, const char **argv) {

	struct pure64_uuid disk_uuid;

	if (pure64_uuid_parse(&disk_uuid, PURE64_DEFAULT_DISK_UUID) != 0) {
		fprintf(stderr, "Failed to parse default disk UUID.\n");
		return EXIT_FAILURE;
	}

	for (int i = 0; i < argc; i++) {
		if (strcmp(argv[i], "--disk-uuid") == 0) {
			if ((i + 1) >= argc) {
				fprintf(stderr, "Disk UUID not given.\n");
				return EXIT_FAILURE;
			}
			if (pure64_uuid_parse(&disk_uuid, argv[i + 1]) != 0) {
				fprintf(stderr, "Invalid disk UUID: %s\n", argv[i + 1]);
				return EXIT_FAILURE;
			}
		}
	}

	int err = pure64_util_mkgpt(util, &disk_uuid);
	if (err != 0) {
		fprintf(stderr, "Failed to make partition table: %s\n", pure64_strerror(err));
		return EXIT_FAILURE;
	}

	return EXIT_SUCCESS;
}

static int pure64_mkfs(struct pure64_util *util, int argc, const char **argv) {
	(void) util;
	(void) argc;
	(void) argv;
	return EXIT_SUCCESS;
}

static int pure64_set_bootsector(struct pure64_util *util, int argc, const char **argv) {

	const void *bootsector_data = NULL;

	uint64_t bootsector_size = 0;

	for (int i = 0; i < argc; i++) {
		if (pure64_strcmp(argv[i], "mbr") == 0) {
			bootsector_data = mbr_data;
			bootsector_size = mbr_data_size;
		} else if (pure64_strcmp(argv[i], "pxe") == 0) {
			bootsector_data = pxe_data;
			bootsector_size = pxe_data_size;
		} else if (pure64_strcmp(argv[i], "multiboot") == 0) {
			bootsector_data = multiboot_data;
			bootsector_size = multiboot_data_size;
		} else if (pure64_strcmp(argv[i], "multiboot2") == 0) {
			bootsector_data = multiboot2_data;
			bootsector_size = multiboot2_data_size;
		} else if (is_opt(argv[i])) {
			fprintf(stderr, "Unknown option: %s\n", argv[i]);
			return EXIT_FAILURE;
		} else {
			fprintf(stderr, "Unknown bootsector: %s\n", argv[i]);
			return EXIT_FAILURE;
		}
	}

	int err = pure64_util_set_bootsector(util, bootsector_data, bootsector_size);
	if (err != 0) {
		fprintf(stderr, "Failed to set bootsector: %s\n", pure64_strerror(err));
		return EXIT_FAILURE;
	}

	return EXIT_SUCCESS;
}

static int pure64_set_stage_two(struct pure64_util *util, int argc, const char **argv) {

	(void) argc;
	(void) argv;

	int err = pure64_util_set_stage_two(util, pure64_data, pure64_data_size);
	if (err != 0) {
		fprintf(stderr, "Failed to set stage two: %s\n", pure64_strerror(err));
		return EXIT_FAILURE;
	}

	return EXIT_SUCCESS;
}

#if 0
static int pure64_cat(struct pure64_fs *fs, int argc, const char **argv) {

	struct pure64_file *file;

	for (int i = 0; i < argc; i++) {

		file = pure64_fs_open_file(fs, argv[i]);
		if (file == NULL) {
			fprintf(stderr, "Failed to open '%s'.\n", argv[i]);
			return EXIT_FAILURE;
		}

		fwrite(file->data, 1, file->data_size, stdout);
	}

	return EXIT_SUCCESS;
}

static int pure64_cp(struct pure64_fs *fs, int argc, const char **argv) {

	int err;
	struct pure64_file *dst;
	FILE *src;
	long int src_size;
	const char *dst_path;
	const char *src_path;

	if (argc <= 0) {
		fprintf(stderr, "Missing source path.\n");
		return EXIT_FAILURE;
	} else if (argc <= 1) {
		fprintf(stderr, "Missing destination path.\n");
		return EXIT_FAILURE;
	}

	src_path = argv[0];
	dst_path = argv[1];

	src = fopen(src_path, "rb");
	if (src == NULL) {
		fprintf(stderr, "Failed to open source file '%s'.\n", src_path);
		return EXIT_FAILURE;
	}

	err = 0;

	err |= fseek(src, 0L, SEEK_END);

	src_size = ftell(src);

	err |= fseek(src, 0L, SEEK_SET);

	if ((err != 0) || (src_size < 0)) {
		fprintf(stderr, "Failed to get file size of '%s'.\n", src_path);
		fclose(src);
		return EXIT_FAILURE;
	}

	err = pure64_fs_make_file(fs, dst_path);
	if (err != 0) {
		fprintf(stderr, "Failed to create destination file '%s': %s.\n", dst_path, pure64_strerror(err));
		fclose(src);
		return EXIT_FAILURE;
	}

	dst = pure64_fs_open_file(fs, dst_path);
	if (dst == NULL) {
		fprintf(stderr, "Failed to open destination file '%s'.\n", dst_path);
		fclose(src);
		return EXIT_FAILURE;
	}

	dst->data = malloc(src_size);
	if (dst->data == NULL) {
		fprintf(stderr, "Failed to allocate memory for destination file '%s'.\n", dst_path);
		fclose(src);
		return EXIT_FAILURE;
	}

	if (fread(dst->data, 1, src_size, src) != ((size_t) src_size)) {
		fprintf(stderr, "Failed to read source file'%s'.\n", src_path);
		fclose(src);
		return EXIT_FAILURE;
	}

	fclose(src);

	dst->data_size = src_size;

	return EXIT_SUCCESS;
}

static int pure64_ls(struct pure64_fs *fs, int argc, const char **argv) {

	struct pure64_dir *subdir;

	if (argc == 0) {
		const char *default_args[] = { "/", NULL };
		return pure64_ls(fs, 1,  default_args);
	}

	for (int i = 0; i < argc; i++) {

		subdir = pure64_fs_open_dir(fs, argv[i]);
		if (subdir == NULL) {
			fprintf(stderr, "Failed to open '%s'.\n", argv[i]);
			return EXIT_FAILURE;
		}

		printf("%s:\n", argv[i]);

		for (uint64_t j = 0; j < subdir->subdir_count; j++)
			printf("dir  : %s\n", subdir->subdirs[j].name);

		for (uint64_t j = 0; j < subdir->file_count; j++)
			printf("file : %s\n", subdir->files[j].name);
	}

	return EXIT_SUCCESS;
}

static int pure64_mkdir(struct pure64_fs *fs, int argc, const char **argv) {

	int err;

	for (int i = 0; i < argc; i++) {
		err = pure64_fs_make_dir(fs, argv[i]);
		if (err != 0) {
			fprintf(stderr, "Failed to create directory '%s'.\n", argv[i]);
			return EXIT_FAILURE;
		}
	}

	return EXIT_SUCCESS;
}
#endif

int main(int argc, const char **argv) {

	int i;
	const char *filename = "pure64.img";

	for (i = 1; i < argc; i++) {
		if (check_opt(argv[i], "help", 'h')) {
			print_help(argv[0]);
			return EXIT_FAILURE;
		} else if (check_opt(argv[i], "file", 'f')) {
			filename = argv[i + 1];
			i++;
		} else if (is_opt(argv[i])) {
			fprintf(stderr, "Unknown option '%s'.\n", argv[i]);
			return EXIT_FAILURE;
		} else {
			break;
		}
	}

	if (filename == NULL) {
		fprintf(stderr, "No filename specified after '--file' or '-f' option.\n");
		return EXIT_FAILURE;
	}

	if (i >= argc) {
		fprintf(stderr, "No command specified (see '--help').\n");
		return EXIT_FAILURE;
	}

	argv = &argv[i];
	argc -= i;

	/* argv[0] should now point to a command. */

	const char *command = argv[0];

	argv = &argv[1];
	argc--;

	/* argv[0] is now the command arguments */

	if (pure64_strcmp(command, "init") == 0) {
		return pure64_init(filename, argc, argv);
	}

	struct pure64_util util;

	pure64_util_init(&util);

	int err = pure64_util_open_disk(&util, filename);
	if (err != 0) {
		fprintf(stderr, "Failed to open '%s': %s\n", filename, pure64_strerror(err));
		pure64_util_done(&util);
		return EXIT_FAILURE;
	}

	int exit_code = EXIT_SUCCESS;

	if (pure64_strcmp(command, "mkgpt") == 0) {
		exit_code = pure64_mkgpt(&util, argc, argv);
	} else if (pure64_strcmp(command, "mkfs") == 0) {
		exit_code = pure64_mkfs(&util, argc, argv);
	} else if (pure64_strcmp(command, "set-bootsector") == 0) {
		exit_code = pure64_set_bootsector(&util, argc, argv);
	} else if (pure64_strcmp(command, "set-stage-two") == 0) {
		exit_code = pure64_set_stage_two(&util, argc, argv);
	} else {

	}

	pure64_util_done(&util);

	return exit_code;
}
